# Generated by Django 2.2.4 on 2019-08-29 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('percent_body_fat', models.FloatField(default=0)),
                ('muscle_mass', models.FloatField(default=0)),
                ('date', models.DateField(default=datetime.date(2019, 8, 29))),
                ('maintenance_calorie', models.FloatField(default=0)),
                ('cutting_calorie', models.FloatField(default=0)),
                ('increasing_calorie', models.FloatField(default=0)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DietModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('protein', models.FloatField()),
                ('carb', models.FloatField()),
                ('fat', models.FloatField()),
                ('date', models.DateField(default=datetime.date(2019, 8, 29))),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('reps', models.IntegerField()),
                ('set', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2019, 8, 29))),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
